"""
Report Generation Prompt Templates

Templates for generating investigation summaries and reports.
"""

from typing import Dict, Any, Optional, List
import json


REPORT_PROMPT_TEMPLATE = """
Generate a formal investigation report based on the following analysis.

ANALYSIS RESULTS:
{analysis_results}

IOCs ANALYZED:
{iocs_summary}

Generate a {report_format} format report with these sections:
1. Executive Summary (2-3 sentences for leadership)
2. Verdict and Severity
3. Technical Findings
4. Timeline (if applicable)
5. Recommended Actions
6. IOCs for Blocking (table format)
7. MITRE ATT&CK Mapping

The report should be suitable for: {audience}
"""

JIRA_REPORT_TEMPLATE = """
Generate a JIRA-compatible investigation summary based on the following analysis.

ANALYSIS RESULTS:
{analysis_results}

Format the output for JIRA with:
- h2. headers
- * bullet points
- {{code}} blocks for technical details
- || table || headers ||

Include: Summary, Severity, Key Findings, Actions, and IOCs table.
"""

MARKDOWN_REPORT_TEMPLATE = """
# Investigation Summary

**Date:** {date}
**Analyst:** Auto-generated
**IOC:** {primary_ioc}

## Verdict
{verdict}

## Executive Summary
{executive_summary}

## Technical Findings
{technical_findings}

## Recommended Actions
{recommended_actions}

## IOCs for Blocking
{iocs_table}

## MITRE ATT&CK Mapping
{mitre_mapping}

---
*Report generated by SecOps Helper AI Analysis*
"""


def build_report_prompt(
    analysis_results: Dict[str, Any],
    report_format: str = "markdown",
    audience: str = "technical"
) -> str:
    """
    Build a report generation prompt from analysis results.

    Args:
        analysis_results: Results from AI analysis
        report_format: Output format (markdown, jira, html)
        audience: Target audience (technical, executive, both)

    Returns:
        Formatted prompt for report generation
    """
    iocs_summary = _format_iocs_summary(analysis_results.get('iocs', {}))

    if report_format == "jira":
        return JIRA_REPORT_TEMPLATE.format(
            analysis_results=json.dumps(analysis_results, indent=2)
        )

    return REPORT_PROMPT_TEMPLATE.format(
        analysis_results=json.dumps(analysis_results, indent=2),
        iocs_summary=iocs_summary,
        report_format=report_format,
        audience=audience
    )


def format_markdown_report(
    analysis_results: Dict[str, Any],
    primary_ioc: str,
    date: Optional[str] = None
) -> str:
    """
    Format analysis results as a Markdown report.

    Args:
        analysis_results: Results from AI analysis
        primary_ioc: The main IOC analyzed
        date: Report date (defaults to current date)

    Returns:
        Formatted Markdown report
    """
    from datetime import datetime

    if date is None:
        date = datetime.now().strftime("%Y-%m-%d")

    # Build verdict section
    verdict = analysis_results.get('verdict', 'UNKNOWN')
    confidence = analysis_results.get('confidence', 0)
    severity = analysis_results.get('severity', 'UNKNOWN')
    verdict_text = f"**{verdict}** ({int(confidence * 100)}% confidence) - Severity: **{severity}**"

    # Build executive summary
    key_findings = analysis_results.get('key_findings', [])
    threat_context = analysis_results.get('threat_context', '')
    executive_summary = threat_context if threat_context else (
        key_findings[0] if key_findings else "Analysis completed."
    )

    # Build technical findings
    findings_text = "\n".join([f"- {f}" for f in key_findings]) if key_findings else "No significant findings."

    # Build recommended actions
    actions = analysis_results.get('recommended_actions', [])
    if actions:
        actions_text = "\n".join([
            f"### {a.get('priority', 'Action').upper()}\n- {a.get('action', '')}: {a.get('details', '')}"
            for a in actions
        ])
    else:
        actions_text = "No specific actions recommended."

    # Build IOCs table
    iocs = analysis_results.get('iocs', {})
    iocs_table = _build_iocs_table(iocs)

    # Build MITRE mapping
    mitre = analysis_results.get('mitre_attack', [])
    mitre_mapping = ", ".join(mitre) if mitre else "Not mapped"

    return MARKDOWN_REPORT_TEMPLATE.format(
        date=date,
        primary_ioc=primary_ioc,
        verdict=verdict_text,
        executive_summary=executive_summary,
        technical_findings=findings_text,
        recommended_actions=actions_text,
        iocs_table=iocs_table,
        mitre_mapping=mitre_mapping
    )


def _format_iocs_summary(iocs: Dict[str, List[str]]) -> str:
    """Format IOCs dictionary as a summary string"""
    lines = []
    for ioc_type, values in iocs.items():
        if values:
            lines.append(f"{ioc_type}: {len(values)} indicator(s)")
    return "\n".join(lines) if lines else "No IOCs identified"


def _build_iocs_table(iocs: Dict[str, List[str]]) -> str:
    """Build a Markdown table of IOCs"""
    if not iocs or not any(iocs.values()):
        return "No IOCs identified for blocking."

    lines = ["| Type | Value | Context |", "|------|-------|---------|"]

    for ioc_type, values in iocs.items():
        for value in values[:10]:  # Limit to 10 per type
            lines.append(f"| {ioc_type} | `{value}` | From analysis |")

    return "\n".join(lines)


def format_json_report(
    analysis_results: Dict[str, Any],
    primary_ioc: str,
    metadata: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Format analysis results as a structured JSON report.

    Args:
        analysis_results: Results from AI analysis
        primary_ioc: The main IOC analyzed
        metadata: Additional metadata to include

    Returns:
        Structured report dictionary
    """
    from datetime import datetime

    return {
        "report": {
            "generated_at": datetime.now().isoformat(),
            "primary_ioc": primary_ioc,
            "tool": "secops-helper",
            "version": "5.0.0"
        },
        "analysis": analysis_results,
        "metadata": metadata or {}
    }
